### ISSUE TITLE
Mouseover delegate event 

### ISSUE THREAD

**Issue by renaudfv** [Ircam-RnD/timeline#8]
I would like to add the mouseover event as a delegate to the timeline in order to use it in my project. Should I make the change an create a pull request?

Renaud

**Comment by b-ma** [comment]
it depends of the need, isn't something like :
```javascript
document.querySelector('#my-timeline').addEventListener('mouseenter', callback);
```
 enough ? if not (maybe precise your use case), we should probably discuss it with @vectorsize

**Comment by renaudfv** [comment]
Yes, it could be done in another way, as long as it delegates the event to the contained segments (I'm using segments in this case). It also is a consistency issue, and yeah we should discuss it.

**Comment by renaudfv** [comment]
Lets talk about the approach, but as you said, dom selection can be used. I was somehow confused on using directly the timeline object event (ex: timeline.on('mouseover', callback)).
